name: Check & fix styling

on: [ push ]

jobs:
    style:
        runs-on: ubuntu-latest
        steps:
            -   name: Git checkout
                uses: actions/checkout@v2
            -   name: Install Dependencies
                run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
            -   name: normalize php
                run: php vendor/bin/phpcbf
            -   uses: stefanzweifel/git-auto-commit-action@v4.0.0
                with:
                    commit_message: Fix formatting with phpcbf
